### ISSUE TITLE
Possible to follow an entry?

### ISSUE THREAD

**Issue by superpikar** [bymayo/craft-follow#2]
Hi, 

found below sentences in the docs

> You simply pass an element ID to it, whether this is a user, category or tag

I want to create like/bookmark functionality similar with instagram.
The use case might be : 
- like/unlike an entry
- bookmark/unbookmark an entry

Does this plugin able to handle above use cases?

**Comment by bymayo** [comment]
@superpikar Sorry this took so long to reply to. I hope you managed to get your project up and running! 

I've been reworking the docs, so if you need it, or anyone else requires this functionality, I put an example together:

See, `Wishlist / Save For Later / Bookmark`
https://plugins.bymayo.co.uk/follow/examples.html#wishlist-save-for-later-bookmark
