### ISSUE TITLE
Just purchased this through Craft and no setting page

### ISSUE THREAD

**Issue by matthewbacon** [bymayo/craft-follow#4]
Just purchased this plugin through CraftCMS and despite copying config.php into my config folder as follow.php I have a blank settings page. Can anyone elaborate on the installation process and examples??

**Comment by matthewbacon** [comment]
![Screenshot 2020-04-07 at 12 42 06](https://user-images.githubusercontent.com/11006446/78665104-315c9000-78cd-11ea-86ca-887676fcf028.png)

**Comment by bymayo** [comment]
@matthewbacon I'll check to see if this is because of Craft 3.4. I haven't checked it on this version. It looks like the styling is a bit off!

In terms of checking to see if a particular user is following another user, try:

```
{% if craft.follow.check(currentUser.id) %}
   <a href="{{ craft.follow.unfollowUrl(user.id) }}">Unfollow User</a>
{% else %}
   <a href="{{ craft.follow.followUrl(user.id) }}">Follow User</a>
{% endif %}
```

I'll try and update the docs with some examples.

**Comment by matthewbacon** [comment]
I am new to all things Craft so I may be on the wrong path but looking at the file structure of my composer installed version of Follow, I don't have a src/templates folder which plugins have. Could this be it?

**Comment by tom-byrom** [comment]
@bymayo @matthewbacon 

I can second this - what exactly is there supposed to be on the settings page? There is no documentation that references it?

Hitting save just creates an error.

Also tried your code example @bymayo , it displays a follow button, but when I click follow nothing changes, it's as if it doesn't think I've followed the user.

Refreshing the profile just keeps giving me the follow link instead of unfollow.

Probably fair to say this plugin is not working how it should....

**Comment by bymayo** [comment]
@tom-byrom I'll look in to this tomorrow. The settings page is likely an error. I don't think there is meant to be a settings page - Only a `follow.php` config file to set options (https://github.com/bymayo/craft-follow#configuration).

Can you paste your code you're using?

Remember, the element you're following/unfollowing has to be passed to it with an ID. In my example, if you're not setting the `user` variable, then it's likely that won't work. In my example this would likely to be being set with a template route. But, try this:

```
{% set user = craft.users.username('someUser').one() %}

{% if craft.follow.check(currentUser.id) %}
   <a href="{{ craft.follow.unfollowUrl(user.id) }}">Unfollow User</a>
{% else %}
   <a href="{{ craft.follow.followUrl(user.id) }}">Follow User</a>
{% endif %}
```
I'll work on some better examples tomorrow also and drop them in the docs.

Hit me up on discord (@bymayo) if you want to figure this out direct.

**Comment by bymayo** [comment]
I'm still fixing the settings page, but I've updated the documentation to help you out with this, I've also added 2 examples:

Users Following / Followers List
https://plugins.bymayo.co.uk/follow/examples.html#users-following-follow-list

News Feed
https://plugins.bymayo.co.uk/follow/examples.html#newsfeed
