### ISSUE TITLE
Getting number of followers not working properly 

### ISSUE THREAD

**Issue by tom-byrom** [bymayo/craft-follow#6]
Hi Jason,
Running the below code returns the incorrect follower numbers for the current user.

The numbers outputted don't seem to represent an obvious pattern because two users with technically the same followers show different follower count, tried to see how the data is stored in the database and can't work out why I'm getting the numbers im getting.

- As you can see from the table the userId 1 is followed by two other users. But the number on the front end is outputted as 5.

- The userId 54 is also followed by 2 users but on the frontend it outputs 3 users?

- And the userId 2 is followed by one user but on the frontend it outputs 2 followers and not 1.

```
{% set myfollowers = craft.follow.followers() %}
<p><span style="font-weight: bold">Total:</span>{{ myfollowers|length }}</p>
```

Thanks
![db-table](https://user-images.githubusercontent.com/34626292/80493593-85ebac00-895d-11ea-84ec-75747d829edf.png)

**Comment by bymayo** [comment]
@tom-byrom I've fixed this in the next release. Should be out in a few days.

**Comment by tom-byrom** [comment]
Awesome mate thanks

**Comment by bymayo** [comment]
@tom-byrom This has now been added to the latest release, I've also updated all the docs, and documented it in there:

https://plugins.bymayo.co.uk/follow/templating.html#available-variables

The reason it doesn't work properly when you use `|length` is that we output the ID's for a user, category etc as a string so your outputted string might have just been 4 chars long.
