### ISSUE TITLE
Update issue - had to revert back to 1.0.1

### ISSUE THREAD

**Issue by tom-byrom** [bymayo/craft-follow#7]
Hi @bymayo 
Just updated to latest version and it started causing issues - little hard to explain on here (I know thats not helpful but just checking if you changed any of the core or just added a few bits in?
Reverting back to 1.0.1 solves my issue. 

I'm using that new Sprig Plugin (reactive components) for Craft to display a list of people you follow in a modal on click.

The code for displaying this info remains the same regardless of Sprigs use.

But on the new version it breaks it and starts throwing errors. Other Follow areas where I have info seem to display fine.

Reverting back to 1.0.1 solves the issue and all is displayed.

Might be something I need to jump on and show you when you get a chance. But wanted to see if anything has been changed to the core workings of the plugin that I might not be aware of?

Thanks

**Comment by bymayo** [comment]
What is exactly causing the issue?

The only major change (See changelog) is that the `check` method now has multiple properties you can set:


https://plugins.bymayo.co.uk/follow/templating.html#check

**Comment by tom-byrom** [comment]
Just upgraded again removed the Sprig component so its rendering the code normally through the template - this is the code that seems to be causing the error.

```
<div id="myModal" class="modal"></div>



  <!-- Modal content -->
  <div class="modal-content">
  <div class="flex justify-content-between">
      <h3>Following</h3>
      <i class="icon-cross close"></i>
  </div>

     {% set users = craft.follow.following() %}
        {% for user in craft.users.id(users) %}
        <div class="flex justify-content-between align-items-center">
          <a class="text-decoration-none flex align-items-center" href="/people/{{ user.username }}">
          {% set optimizedAuthorPic = user.getPhoto().authorPic %}
              <img class="profile_pic_sml lazyload" 
              src="{{ optimizedAuthorPic.placeholderBox() }}"
              data-srcset="{{ optimizedAuthorPic.srcset() }}"
              sizes="(max-width: 100vw) 64px" />
              <div>
                <span class="following_username">{{ user.username }} </span><br />
                <span class="following_friendlyname">{{ user.friendlyName }}</span>
              </div>
          </a>
          {% if craft.follow.check(user.id) %}
          <a class="btn btn-outline-primary" href="{{ craft.follow.unfollowUrl(user.id) }}">Unfollow</a>
          {% else %}
          <a class="text-decoration-none" href="{{ craft.follow.followUrl(user.id) }}">Follow</a>
          {% endif %}
        </div>
        {% endfor %}
  </div>
```
I then get this error - bare in mind I have other follow elements on the page but they all seem to display fine just when I add the above code I get the problem.

![Annotation 2020-06-20 164215](https://user-images.githubusercontent.com/34626292/85205724-09e66280-b315-11ea-8db0-ec2b64894e63.png)

**Comment by tom-byrom** [comment]
Just downgraded to 1.0.1 again and the page runs with no error.

**Comment by bymayo** [comment]
Change:

```
{% if craft.follow.check(user.id) %}
```

To:

```
{% if craft.follow.check({ elementId: user.id }) %}
```

As per updated docs (See the `check` method):
https://plugins.bymayo.co.uk/follow/templating.html#check

I'll put a note that this is a breaking change in the docs.

The reason I've done this, is because I want to add more parameters to the `check` method in future. So I had to make it have the ability to set multiple values. Rather than 1, like you currently have.

**Comment by tom-byrom** [comment]
Cool all done thanks @bymayo. 

Adding more params to the check in the future sounds good too.
